name: Server
    on: workflow_dispatch
    jobs:
      start_serv:
      runs-on: [ubuntu-latest]
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@v1
          with:
            python-version: '3.10.19'
            architecture: 'x64'
        - name: Start serv
          run: uvicorn main:app --reload